name: vitto-credit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - notebook
  - pip
  - pip:
      - xgboost
      - imbalanced-learn
